name: Deploy to prod
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm -v
  build:
    needs: 
      - test
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: echo pippo